ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('ecommercewebapp.urls'))
]

ecommerce/ecommercewebapp/urls.py
from django.urls import path,re_path
from .views import (
    products,
    productDetail,
    search_by_catagory,
    search_by_label,
    search_by_badge,
    item_list_view_by_tags,
    search,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    ordersummary,
    delete_item,
    checkout,
    load_cities,
    addCouponView
)
from django.conf.urls.static import static
from django.conf import settings
app_name='ecommercewebapp'
urlpatterns = [
    path('',products.as_view(),name='home'),
    path('product/<slug>/',productDetail, name='product'),
    path('search/',search, name='search'),
    path('catagory/<str:catagory>',search_by_catagory,name='catagory'),
    path('label/<str:label>',search_by_label,name='label'),
    path('badge/<str:badge>',search_by_badge,name='badge'),
    path('tag/?P<tag_slug>[-\w]+/',item_list_view_by_tags,name='items_by_tag'),
    path('addtocart/<slug>',add_to_cart,name='add_to_cart'),
    path('removefromcart/<slug>',remove_from_cart,name='remove_from_cart'),
    path('removesingleitemfromcart/<slug>',remove_single_item_from_cart,name='remove_single_item_from_cart'),
    path('order-summary',ordersummary.as_view(),name='order_summary'),
    path('delete-item/<slug>',delete_item,name='delete_item'),
    path('checkout/',checkout.as_view(),name='checkout'),
    path('ajax/load-cities',load_cities,name='ajax_load_cities'),
    path('add-coupon/',addCouponView.as_view(),name='add-coupon'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommercewebapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.text import slugify
from django.shortcuts import reverse
from taggit.managers import TaggableManager
from cities_light.models import Country,City,Region

CATAGORY_CHOICES=(
    ('Breaker','Breaker'),
    ('VFD','VFD'),
    ('Steam Turbine','Steam Turbine'),
    ('Gas Turbine','Gas Turboine'),
    ('Transformer','Transformer'),
    ('Motor','Motor'),
    ('Other','Other')
)
LABEL_CHOICES=(
    ('Human Safety','Human Safety'),
    ('Energy Saving','Energy Saving'),
    ('Reliability Enhancement','Reliability Enhancement'),
)
BADGE_CATAGORY=(
    ('Best Seller','Best Seller'),
    ('Most Reliable','Most Reliable'),
    ('Top Performer','Top performer')
)
ADDRESS_CHOICES=(
    ('S','Shipping'),
    ('B','Billing')
)

class MyUser(AbstractUser):
    email=models.EmailField(unique=True)
    def __str__(self):
        return self.first_name
    pass
class Profile(models.Model):
    user=models.OneToOneField(MyUser,on_delete=models.CASCADE)
    avatar=models.ImageField(upload_to='avatar/%Y/%m/%d',null=True,blank=True)

    def __str__(self):
        return self.user.first_name+" "+self.user.last_name
class Item(models.Model):
    title=models.CharField(max_length=250)
    price=models.FloatField()
    discountPercentage=models.IntegerField(null=True,blank=True)
    catagory=models.CharField(choices=CATAGORY_CHOICES,max_length=30,null=True)
    label=models.CharField(choices=LABEL_CHOICES,max_length=50,null=True)
    badge=models.CharField(choices=BADGE_CATAGORY,max_length=50,null=True)
    slug=models.SlugField(max_length=255,unique=True, null=True, blank=True)
    img=models.ImageField()
    description=models.TextField(null=True)
    tags=TaggableManager()
    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)
        super(Item, self).save(*args, **kwargs)
    def get_absolute_url(self):
        return reverse('ecommercewebapp:product',kwargs={
            'slug':self.slug
        })
    def get_total_discounted_price(self):
        return self.price-(self.price*(self.discountPercentage/100))
    def get_absolute_url_catagory(self):
        return reverse('ecommercewebapp:catagory',kwargs={
            'catagory':self.catagory
        })
    def get_absolute_url_by_label(self):
        return reverse('ecommercewebapp:label',kwargs={
            'label':self.label
        })
    def get_absolute_url_by_badge(self):
        return reverse('ecommercewebapp:badge',kwargs={'badge':self.badge})
    def add_to_cart(self):
        return reverse('ecommercewebapp:add_to_cart',kwargs={'slug':self.slug})
    def remove_from_cart(self):
        return reverse('ecommercewebapp:remove_from_cart',kwargs={'slug':self.slug})
class OrderItem(models.Model):
    user=models.ForeignKey(MyUser,on_delete=models.CASCADE)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    ordered=models.BooleanField(default=False)
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    def total_item_price(self):
        return self.item.price*self.quantity
    def total_price(self):
        if self.item.discountPercentage:
            return self.quantity*self.item.get_total_discounted_price()
        else:
            return self.total_item_price()
    def amount_saved(self):
        return self.total_item_price()-(self.total_price())
class Order(models.Model):
    user=models.ForeignKey(MyUser,on_delete=models.CASCADE)
    items=models.ManyToManyField(OrderItem)
    start_date=models.DateField(auto_now_add=True)
    order_date=models.DateField()
    coupon=models.ForeignKey('Coupon',on_delete=models.SET_NULL,null=True,blank=True)
    Ordered=models.BooleanField(default=False)
    shipping_address=models.ForeignKey('Address',related_name='shipping_address',on_delete=models.SET_NULL,blank=True, null=True)
    billing_address=models.ForeignKey('Address',related_name='billing_address',on_delete=models.SET_NULL,blank=True, null=True)

    def total_order_price(self):
        total=0
        for cart_item in self.items.all():
            total+=cart_item.total_price()
        if self.coupon:
            total-=self.coupon.amount
        return total

        return total
    def total_order_price2(self):
        total=0
        for cart_item in self.items.all():
            total+=cart_item.total_price()
        return total

        return total
    def total_amount_saved(self):
        total_saved=0
        for cart_item in self.items.all():
            total_saved+=cart_item.amount_saved()
        return total_saved
class Address(models.Model):
    user=models.ForeignKey(MyUser,on_delete=models.CASCADE)
    street_address=models.CharField(max_length=255,default='Pakistan')
    country=models.ForeignKey(Country,on_delete=models.CASCADE)
    city=models.ForeignKey(City,on_delete=models.CASCADE)
    address_type=models.CharField(max_length=255,choices=ADDRESS_CHOICES,default='S')
    default=models.BooleanField(default=False)
    class Meta:
        verbose_name_plural='Addresses'
class Coupon(models.Model):
    code=models.CharField(max_length=15,null=True,blank=True)
    amount=models.FloatField(default=0.0)
    def __str__(self):
        return self.code

ecommerce/ecommercewebapp/forms.py
from django import forms
from .models import Address,Coupon
from cities_light.models import City
class checkoutform(forms.ModelForm):
    class Meta:
        model=Address
        fields=['country','city','street_address']
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['city'].queryset=City.objects.none()
        if 'country' in self.data:
            try:
                country=self.data.get('country')
                self.fields['city'].queryset=City.objects.filter(country=country)
            except(ValueError,TypeError):
                print('error in city')
class couponform(forms.Form):
    code=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control',
        'placeholder':'Promo Code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))

ecommerce/ecommercewebapp/views.py
import random
import string
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Item, OrderItem,Order,Address,Coupon
from taggit.models import Tag
from django.views.generic import ListView,DetailView,View,CreateView
from django.shortcuts import get_object_or_404,redirect
from django.db.models import Count
from django.contrib.postgres.search import SearchVector,SearchQuery,SearchRank
from django.contrib.postgres.aggregates import StringAgg
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from .forms import checkoutform,couponform
from cities_light.models import Country,City
def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))
class products(ListView):
    model = Item
    template_name = 'ecommercewebapp/products.html'
def productDetail(request,slug):
    item=get_object_or_404(Item,slug=slug)
    item_tags_ids=item.tags.values_list('id',flat=True)
    similar_items=Item.objects.filter(tags__in=item_tags_ids).exclude(id=item.id)
    similar_items=similar_items.annotate(same_tag=Count('tags'))
    context={
        'item':item,
        'similar_items':similar_items,
    }
    return render(request,'ecommercewebapp/product.html',context)
def search_by_catagory(request,catagory):
    items=Item.objects.filter(catagory=catagory)
    context={
        'items':items,
        'catagory':catagory
    }
    return render(request,'ecommercewebapp/search_by_catagory.html',context)
def search_by_label(request,label):
    items=Item.objects.filter(label=label)
    context={
        'items':items,
        'label':label
    }
    return render(request,'ecommercewebapp/search_by_label.html',context)
def search_by_badge(request,badge):
    items=Item.objects.filter(badge=badge)
    context={
        'badge':badge,
        'items':items
    }
    return render(request,'ecommercewebapp/search_by_badge.html',context)
def item_list_view_by_tags(request,tag_slug):
    tag=get_object_or_404(Tag,slug=tag_slug)
    items=Item.objects.all()
    items=items.filter(tags__in=[tag])
    context={
        'tag':tag,
        'items':items
    }
    return render(request,'ecommercewebapp/items_list_by_tags.html',context)
def search(request):
    try:
        q=request.GET.get('q')
    except:
        q='Please enter the query'
    if q:
        query=SearchQuery(q)
        vector=SearchVector('catagory',weight='A')+SearchVector(StringAgg('tags__name',weight='B',delimiter=','))
        rate=SearchRank(vector,query)
        items=Item.objects.annotate(rank=rate).order_by('-rank')
        context={
            'items':items,
            'query':q
        }
        return render(request,'ecommercewebapp/search.html',context)
    else:
        items=Item.objects.all()
        context={
            'query':q,
            'items':items
        }
        return render(request,'ecommercewebapp/nosearch.html',context)

@login_required
def add_to_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)
    order_item,created=OrderItem.objects.get_or_create(
        item=item,
        user=request.user,
        ordered=False
    )
    order_qs=Order.objects.filter(user=request.user,Ordered=False)
    print(order_qs)
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=slug).exists():
            order_item.quantity+=1
            order_item.save()
            return redirect('ecommercewebapp:order_summary')
        else:
            order.items.add(order_item)
            return redirect('ecommercewebapp:product',slug=slug)
    else:
        start_date=timezone.now()
        order_date=timezone.now()
        order=Order.objects.create(user=request.user,order_date=order_date,start_date=start_date)
        order.items.add(order_item)
        return redirect('ecommercewebapp:order_summary')
def remove_single_item_from_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)
    order_item = OrderItem.objects.filter(item=item, user=request.user, ordered=False)[0]
    order_qs=Order.objects.filter(user=request.user,Ordered=False)
    if order_qs.exists():
        order=order_qs[0]
        if order.items.filter(item__slug=slug).exists():
            if order_item.quantity>1:
                order_item.quantity-=1
                order_item.save()
                return redirect("ecommercewebapp:order_summary")
            else:
                order_item.quantity=1
                return redirect("ecommercewebapp:order_summary")
def remove_from_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)
    order_qs=Order.objects.filter(user=request.user,Ordered=False)
def delete_item(request,slug):
    item=get_object_or_404(Item,slug=slug)
    order_item=OrderItem.objects.get(item=item,user=request.user,ordered=False)
    order=Order.objects.filter(user=request.user,Ordered=False)[0]
    order.items.remove(order_item)
    order_item.delete()
    if not order.items.all():
        return redirect("ecommercewebapp:home")
    else:
        return redirect("ecommercewebapp:order_summary")


class ordersummary(LoginRequiredMixin,View):
    def get(self,*args,**kwargs):
        try:
            order = Order.objects.get(user=self.request.user, Ordered=False)
            context={
                'object':order
            }
            return render(self.request, 'ecommercewebapp/order_summary.html', context)
        except ObjectDoesNotExist:
            redirect('/')
class checkout(CreateView):
    def get(self,*args,**kwargs):
        try:
            order=Order.objects.get(user=self.request.user,Ordered=False)
            form=checkoutform()
            copform=couponform()
            context={
                'form':form,
                'order':order,
                'couponform':copform
            }
            shipping_address_qs=Address.objects.filter(user=self.request.user,address_type='S',default=True)
            if shipping_address_qs.exists():
                context.update({
                    'default_shipping_address':shipping_address_qs
                })
            billing_address_qs=Address.objects.filter(user=self.request.user,address_type='B',default=True)
            if billing_address_qs.exists():
                context.update({

                    'default_billing_address':billing_address_qs[0]
                })
            return render(self.request, 'ecommercewebapp/checkout.html', context)
        except ObjectDoesNotExist:
            messages.info(self.request,'You donot have an active order')
            return redirect('ecommercewebapp:checkout')


    def post(self,*args,**kwargs):
        form=checkoutform(self.request.POST or None, self.request.FILES or None, )
        if form.is_valid():
            form.instance.user=self.request.user
            form.save(commit=True)
            return redirect('ecommercewebapp:home')
        else:
            print(form.errors)
            return render(self.request,'ecommercewebapp/checkout.html',{'errors': form.errors, 'form':form})
def load_cities(request):
    country_id=request.GET.get('country')
    cities=City.objects.filter(country=country_id)
    return render(request,'ecommercewebapp/city_dropdown.html', {'cities':cities})
def get_coupon(request,code):
    try:
        couponcode=Coupon.objects.get(code=code)
        return couponcode
    except ObjectDoesNotExist:
        return None
class addCouponView(View):
    def post(self,*args,**kwargs):
        form=couponform(self.request.POST or None)
        if form.is_valid():
            try:
                code=form.cleaned_data.get('code')
                order=Order.objects.get(user=self.request.user,Ordered=False)
                order.coupon=get_coupon(self.request,code)
                if order.coupon==None:
                    messages.info(self.request,'this copoun does  not exists')
                else:
                    messages.info(self.request, 'code has been redeemed')
                order.save()
                return redirect('ecommercewebapp:checkout')
            except ObjectDoesNotExist:
                messages.info(self.request,'you do not have an active order')
                return redirect('ecommercewebapp:checkout')
        else:
            print(form.errors)
            return render(self.request, 'ecommercewebapp/checkout.html', {'errors': form.errors, 'form': form})

ecommerce/templates/ecommercewebapp/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Shahab Ecommerce</title>
  {%include 'ecommercewebapp/css.html' %}
</head>
{% include 'ecommercewebapp/navbar.html' %}
<body>
{%block content%}
{% endblock content%}
{% include "ecommercewebapp/footer.html" %}
{% include "ecommercewebapp/scripts.html" %}
</body>

</html>

ecommerce/templates/ecommercewebapp/carousel.html
<!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('/static/img/2.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Industrial Store</strong>
              </h1>

              <p>
                <strong>Buy all technical stuff for industries</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>Breaker, pump, motors , generators, relays, PLC, DBs, cables, blower, belts any thing related to industry</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
       <div class="carousel-item">
        <div class="view" style="background-image: url('/static/img/1.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Industrial Store</strong>
              </h1>

              <p>
                <strong>Buy all technical stuff for industries</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>Breaker, pump, motors , generators, relays, PLC, DBs, cables, blower, belts any thing related to industry</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->

      <!--Third slide-->
       <div class="carousel-item">
        <div class="view" style="background-image: url('/static/img/3.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Industrial Store</strong>
              </h1>

              <p>
                <strong>Buy all technical stuff for industries</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>Breaker, pump, motors , generators, relays, PLC, DBs, cables, blower, belts any thing related to industry</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Third slide-->

    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

ecommerce/templates/ecommercewebapp/catagorynavbar.html
<!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Oil filled</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Dry type</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Transformer oil tester</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

ecommerce/templates/ecommercewebapp/checkout.html
{% extends 'ecommercewebapp/base.html'%}
{%load static%}
{%block content%}
  <!--Main layout-->
<main class="mt-5 pt-4">
   <form action="/checkout/" method="POST" id="addressForm" data-cities-url="{% url 'ecommercewebapp:ajax_load_cities' %}">
       {%csrf_token%}
       {{form.as_p}}
        <div>
    </div>
              <button type="submit">Submit</button>
{% if errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
   </form>
<form action="{%url  'ecommercewebapp:add-coupon'%}" method="post">
    {%csrf_token%}
    {{couponform.as_p}}
    <button type="submit">Redeem</button>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}</form>
    <div>
        {%for cart_item in order.items.all%}
        <p>Item Title:{{cart_item.item.title}}</p>
        <p>Item Price:{{cart_item.item.price}}</p>
        <p>Discounted percentage:{{cart_item.item.discountPercentage}}%</p>
        <p>Quantity:{{cart_item.quantity}}</p>
        <p>Total Order price:{{order.total_order_price}}</p>
        <p>Amount Saved:{{order.total_amount_saved}}</p>
        <p>Coupon amount:{{order.coupon.amount}}</p>
        <p>Subtracting coupon amount and total price of order after coupon amount:{{order.total_order_price}}</p>
        {%endfor%}
        <p>{{default_shipping_address}}</p>
        <p>{{default_billing_address}}</p>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
             $("#id_country").change(function () {
              var url = $("#addressForm").attr("data-cities-url");
              var countryId = $(this).val();

              $.ajax({
                url: url,
                data: {
                  'country': countryId
                },
                success: function (data) {
                  $("#id_city").html(data);
                }
              });

            });
      </script>

</main>
{%endblock content%}

ecommerce/templates/ecommercewebapp/city_dropdown.html
<option value="">Select City</option>
{%for city in cities%}
<option value="{{city.pk}}">{{city.name}}</option>
{%endfor%}

ecommerce/templates/ecommercewebapp/footer.html
 <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="/" target="_blank"
        role="button">store # 6
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="/" target="_blank" role="button">
        Contact Us
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/sklaghari" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/sklaghari" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://youtu.be/9A7TMiqOc04" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>
      <a href="https://github.com/sklaghari" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2020 Copyright:
      <a href="/" target="_blank"> sulfursoft.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

ecommerce/templates/ecommercewebapp/nosearch.html
{%extends 'ecommercewebapp/base.html'%}
{%block content%}
{%include 'ecommercewebapp/carousel.html'%}
  <!--Main layout-->
  <main>
    <div class="container">
      {%include 'ecommercewebapp/catagorynavbar.html'%}
      <!--Section: Products v.3-->
      <h1><strong>Please enter something for search Thanks buddy</strong></h1>
       <div class="row wow fadeIn">
          {%for item in items%}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">
            <!--Card-->
            <div class="card" >
              <!--Card image-->
              <div class="view overlay"><img src="{{item.img.url}}" class="card-img-top" alt="">
                <a href="{{ item.get_absolute_url }}"><div class="mask rgba-white-slight"></div></a>
              </div>
              <!--Card image-->
              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text"><h5>{{item.catagory|linebreaks}}</h5></a>
                <h5><strong>
                    <a href="" class="dark-grey-text">{{item.title|linebreaks|truncatechars:33}}<span class="badge badge-pill success-color">{{item.badge|linebreaks}}</span></a>
                  </strong></h5>
                {%if item.discountPercentage%}
                <h4 class="font-weight-bold blue-text"><del>{{item.price}}PKR</del></h4>
                <h4 class="font-weight-bold red-text"><strong>{{item.get_total_discounted_price}}</strong></h4>
                <h4 class="font-weight-bold red-text"><strong>Discount:{{item.discountPercentage}}%</strong></h4>
                {%else%}
                <h4 class="font-weight-bold red-text"><strong>{{item.price}}</strong></h4>
                {%endif%}
              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
        {%endfor%}
        </div>
        <!--Grid row-->
      </section>
      <!--Section: Products v.3-->
      {%include 'ecommercewebapp/pagination.html'%}
    </div>
    </div>
  </main>
  <!--Main layout-->
{%endblock%}